server:
  port: 8088
  max-http-header-size: 102400
logging:
  config: classpath:logback.xml

spring:
  application:
    name: database
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        enabled: true
  boot:
    admin:
      client:
        # 设置 Spring Boot Admin Server 地址
        url: http://localhost:9999
        instance:
          prefer-ip: true # 注册实例时，优先使用 IP

# Actuator 监控端点的配置项
management:
  endpoints:
    web:
      # Actuator 提供的 API 接口的根目录。默认为 /actuator
      base-path: /actuator
      exposure:
        # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。
        include: '*'
  # 已存在日志xml配置文件后，需要配置该项
  endpoint:
    logfile:
      external-file: ./logs/sys-console.log
