spring:
  application:
    name: gateway
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: @profileAcitve@
logging:
  config: classpath:logback-@profileAcitve@.xml

management:
  endpoints:
    web:
      exposure:
        include:  '*'
